def load():
    return [("Brigham Young", "BYU"),
            ("Cal State Long Beach", "Long Beach State"),
            ("Central Connecticut State", "Central Connecticut"),
            ("Central Florida", "UCF"),
            ("Connecticut", "UConn"),
            ("Detroit Mercy", "Detroit"),
            ("East Tennessee State", "ETSU"),
            ("Illinois-Chicago", "UIC"),
            ("Long Island University", "LIU"),
            ("Louisiana State", "LSU"),
            ("Maryland-Baltimore County", "UMBC"),
            ("Massachusetts", "UMass"),
            ("Mississippi", "Ole Miss"),
            ("Nevada-Las Vegas", "UNLV"),
            ("North Carolina", "UNC"),
            ("North Carolina State", "NC State"),
            ("North Carolina-Asheville", "UNC Asheville"),
            ("North Carolina-Greensboro", "UNC Greensboro"),
            ("North Carolina-Wilmington", "UNC Wilmington"),
            ("Pennsylvania", "Penn"),
            ("Pittsburgh", "Pitt"),
            ("Saint Joseph\'s", "St. Joseph\'s"),
            ("Saint Mary\'s (CA)", "Saint Mary\'s"),
            ("Saint Peter\'s", "St. Peter\'s"),
            ("Southern California", "USC"),
            ("Southern Methodist", "SMU"),
            ("Southern Mississippi", "Southern Miss"),
            ("Texas Christian", "TCU"),
            ("Texas-El Paso", "UTEP"),
            ("Texas-San Antonio", "UTSA"),
            ("UC-Santa Barbara", "UCSB"),
            ("University of California", "California"),
            ("Virginia Commonwealth", "VCU")]
