brackets = {
    1:  # For testing
        [
            ('Gonzaga',1),
            ('Georgia State',16),
            ('Boise State',8),
            ('Memphis',9),
        ],

    2023:
        [
            ('Alabama',1),
            ('Texas A&M/Southeast Missouri State',16),
            ('Maryland',8),
            ('West Virginia',9),
            ('San Diego State',5),
            ('College of Charleston',12),
            ('Virginia',4),
            ('Furman',13),
            ('Creighton',6),
            ('NC State',11),
            ('Baylor',3),
            ('UC Santa Barbara',14),
            ('Missouri',7),
            ('Utah State',10),
            ('Arizona',2),
            ('Princeton',15),
            ('Purdue',1),
            ('Texas Southern/Fairleigh Dickinson',16),
            ('Memphis',8),
            ('Florida Atlantic',9),
            ('Duke',5),
            ('Oral Roberts',12),
            ('Tennessee',4),
            ('Louisiana',13),
            ('Kentucky',6),
            ('Providence',11),
            ('Kansas State',3),
            ('Montana State',14),
            ('Michigan State',7),
            ('Southern California',10),
            ('Marquette',2),
            ('Vermont',15),
            ('Houston',1),
            ('Northern Kentucky',16),
            ('Iowa',8),
            ('Auburn',9),
            ('Miami (FL)',5),
            ('Drake',12),
            ('Indiana',4),
            ('Kent State',13),
            ('Iowa State',6),
            ('Pittsburgh/Mississippi State',11),
            ('Xavier',3),
            ('Kennesaw State',14),
            ('Texas A&M-Corpus Christi',7),
            ('Penn State',10),
            ('Texas',2),
            ('Colgate',15),
            ('Kansas',1),
            ('Howard',16),
            ('Arkansas',8),
            ('Illinois',9),
            ('Saint Mary\'s (CA)',5),
            ('Virginia Commonwealth',12),
            ('Connecticut',4),
            ('Iona',13),
            ('TCU',6),
            ('Arizona State/Nevada',11),
            ('Gonzaga',3),
            ('Grand Canyon',14),
            ('Northwestern',7),
            ('Boise State',10),
            ('UCLA',2),
            ('UNC Asheville',15),
        ],

    2022:
        [
            ('Gonzaga',1),
            ('Georgia State',16),
            ('Boise State',8),
            ('Memphis',9),
            ('UConn',5),
            ('New Mexico State',12),
            ('Arkansas',4),
            ('Vermont',13),
            ('Alabama',6),
            ('Notre Dame',11),
            ('Texas Tech',3),
            ('Montana State',14),
            ('Michigan State',7),
            ('Davidson',10),
            ('Duke',2),
            ('Cal State Fullerton',15),
            ('Baylor',1),
            ('Norfolk State',16),
            ('UNC',8),
            ('Marquette',9),
            ("Saint Mary's",5),
            ('Indiana',12),
            ('UCLA',4),
            ('Akron',13),
            ('Texas',6),
            ('Virginia Tech',11),
            ('Purdue',3),
            ('Yale',14),
            ('Murray State',7),
            ('San Francisco',10),
            ('Kentucky',2),
            ("St. Peter's",15),
            ('Arizona',1),
            ('Wright State',16),
            ('Seton Hall',8),
            ('TCU',9),
            ('Houston',5),
            ('UAB',12),
            ('Illinois',4),
            ('Chattanooga',13),
            ('Colorado State',6),
            ('Michigan',11),
            ('Tennessee',3),
            ('Longwood',14),
            ('Ohio State',7),
            ('Loyola (IL)',10),
            ('Villanova',2),
            ('Delaware',15),
            ('Kansas',1),
            ('Texas Southern',16),
            ('San Diego State',8),
            ('Creighton',9),
            ('Iowa',5),
            ('Richmond',12),
            ('Providence',4),
            ('South Dakota State',13),
            ('LSU',6),
            ('Iowa State',11),
            ('Wisconsin',3),
            ('Colgate',14),
            ('USC',7),
            ('Miami (FL)',10),
            ('Auburn',2),
            ('Jacksonville State',15),
        ],

    2021:
        [
            ('Gonzaga',1),
            ('Norfolk State',16),
            ('Oklahoma',8),
            ('Missouri',9),
            ('Creighton',5),
            ('UCSB',12),
            ('Virginia',4),
            ('Ohio',13),
            ('USC',6),
            ('Drake',11),
            ('Kansas',3),
            ('Eastern Washington',14),
            ('Oregon',7),
            ('VCU',10),
            ('Iowa',2),
            ('Grand Canyon',15),
            ('Michigan',1),
            ('Texas Southern',16),
            ('LSU',8),
            ('St. Bonaventure',9),
            ('Colorado',5),
            ('Georgetown',12),
            ('Florida State',4),
            ('UNC Greensboro',13),
            ('BYU',6),
            ('UCLA',11),
            ('Texas',3),
            ('Abilene Christian',14),
            ('UConn',7),
            ('Maryland',10),
            ('Alabama',2),
            ('Iona',15),
            ('Baylor',1),
            ('Hartford',16),
            ('UNC',8),
            ('Wisconsin',9),
            ('Villanova',5),
            ('Winthrop',12),
            ('Purdue',4),
            ('North Texas',13),
            ('Texas Tech',6),
            ('Utah State',11),
            ('Arkansas',3),
            ('Colgate',14),
            ('Florida',7),
            ('Virginia Tech',10),
            ('Ohio State',2),
            ('Oral Roberts',15),
            ('Illinois',1),
            ('Drexel',16),
            ('Loyola (IL)',8),
            ('Georgia Tech',9),
            ('Tennessee',5),
            ('Oregon State',12),
            ('Oklahoma State',4),
            ('Liberty',13),
            ('San Diego State',6),
            ('Syracuse',11),
            ('West Virginia',3),
            ('Morehead State',14),
            ('Clemson',7),
            ('Rutgers',10),
            ('Houston',2),
            ('Cleveland State',15)
        ],

    2019:
        [
            ("Duke",1),
            ("North Dakota State",16),
            ("VCU",8),
            ("UCF",9),
            ("Mississippi State",5),
            ("Liberty",12),
            ("Virginia Tech",4),
            ("Saint Louis",13),
            ("Maryland",6),
            ("Belmont",11),
            ("LSU",3),
            ("Yale",14),
            ("Louisville",7),
            ("Minnesota",10),
            ("Michigan State",2),
            ("Bradley",15),
            ("Gonzaga",1),
            ("Fairleigh Dickinson",16),
            ("Syracuse",8),
            ("Baylor",9),
            ("Marquette",5),
            ("Murray State",12),
            ("Florida State",4),
            ("Vermont",13),
            ("Buffalo",6),
            ("Arizona State",11),
            ("Texas Tech",3),
            ("Northern Kentucky",14),
            ("Nevada",7),
            ("Florida",10),
            ("Michigan",2),
            ("Montana",15),
            ("Virginia",1),
            ("Gardner-Webb",16),
            ("Ole Miss",8),
            ("Oklahoma",9),
            ("Wisconsin",5),
            ("Oregon",12),
            ("Kansas State",4),
            ("UC-Irvine",13),
            ("Villanova",6),
            ("Saint Mary's",11),
            ("Purdue",3),
            ("Old Dominion",14),
            ("Cincinnati",7),
            ("Iowa",10),
            ("Tennessee",2),
            ("Colgate",15),
            ("UNC",1),
            ("Iona",16),
            ("Utah State",8),
            ("Washington",9),
            ("Auburn",5),
            ("New Mexico State",12),
            ("Kansas",4),
            ("Northeastern",13),
            ("Iowa State",6),
            ("Ohio State",11),
            ("Houston",3),
            ("Georgia State",14),
            ("Wofford",7),
            ("Seton Hall",10),
            ("Kentucky",2),
            ("Abilene Christian",15)
        ],

    2018:
        [
            ("Virginia",1),
            ("UMBC",16),
            ("Creighton",8),
            ("Kansas State",9),
            ("Kentucky",5),
            ("Davidson",12),
            ("Arizona",4),
            ("Buffalo",13),
            ("Miami (FL)",6),
            ("Loyola (IL)",11),
            ("Tennessee",3),
            ("Wright State",14),
            ("Nevada",7),
            ("Texas",10),
            ("Cincinnati",2),
            ("Georgia State",15),
            ("Xavier",1),
            ("Texas Southern",16),
            ("Missouri",8),
            ("Florida State",9),
            ("Ohio State",5),
            ("South Dakota State",12),
            ("Gonzaga",4),
            ("UNC Greensboro",13),
            ("Houston",6),
            ("San Diego State",11),
            ("Michigan",3),
            ("Montana",14),
            ("Texas A&M",7),
            ("Providence",10),
            ("UNC",2),
            ("Lipscomb",15),
            ("Villanova",1),
            ("Radford",16),
            ("Virginia Tech",8),
            ("Alabama",9),
            ("West Virginia",5),
            ("Murray State",12),
            ("Wichita State",4),
            ("Marshall",13),
            ("Florida",6),
            ("St. Bonaventure",11),
            ("Texas Tech",3),
            ("Stephen F. Austin",14),
            ("Arkansas",7),
            ("Butler",10),
            ("Purdue",2),
            ("Cal State Fullerton",15),
            ("Kansas",1),
            ("Penn",16),
            ("Seton Hall",8),
            ("NC State",9),
            ("Clemson",5),
            ("New Mexico State",12),
            ("Auburn",4),
            ("College of Charleston",13),
            ("TCU",6),
            ("Syracuse",11),
            ("Michigan State",3),
            ("Bucknell",14),
            ("Rhode Island",7),
            ("Oklahoma",10),
            ("Duke",2),
            ("Iona",15)
        ]
    }



